order/urls.py
from django.urls import path 
from .views import * 

app_name= 'order' 

urlpatterns = [
    path('new/<int:store_id>/', new_order, name='new-order'), 
    path('new/select-store/', select_store, name='select-store'),
    path('order-sent/', order_sent, name='order-sent'), 
    path('update_products_select/<int:store_id>/', update_products_select, name='update-products-select'), 
    path('details/<str:number>/', show_order, name='show-order'), 
]

page/urls.py
from django.urls import path 
from .views import * 

app_name= 'page'

urlpatterns = [
    path('', index, name='index'), 
    path('about/', about, name='about'), 
    path('terms-and-conditions/', terms_conditions, name='terms-conditions'), 
    path('return-policy/', return_policy, name='return-policy'), 
    path('privacy-policy/', privacy_policy, name='privacy-policy'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls', namespace='page')), 
    path('user/', include('user.urls', namespace='user')), 
    path('order/', include('order.urls', namespace='order')), 
    path('invoice/', include('invoice.urls',namespace='invoice')), 
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page/templates/page/about.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    من نحن؟
{% endblock title %}
    

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock stylesheets %}
    

{% block content %}
    
    <main>
        <div class="container">
            <section class="content">
                <h2 class="title">من نحن؟</h2>
                <p>خدمة فزعه خدمة مقدمة من مؤسسة خيارات السداد للتجارة
                    تتيح من خلالها امكانية العميل من اعادة بيع مشترواته
                    وذلك من خلال استلام مشتروات العميل و توفير مشتري فوري وتحويل المبلغ الى حساب العميل الذي يتم ادخاله اثناء عملية الطلب
                </p>
                <p>
                    خدمة فزعه
                    مؤسسة خيارات السداد للتجارة (3550150985)
                    تبوك - حي الربوه
                    خدمة العملاء 0570767020    
                </p>
            </section>
        </div>
    </main>

{% endblock content %}

page/templates/page/home.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    الصفحة الرئيسية
{% endblock title %}
    

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock stylesheets %}



{% block content %}
    
    
<main>
        <div class="container">
            <img src="images/01.png" alt="" class="big-img">
            
            {% if messages %}
            
            {% for msg in messages %}
                <h2 class="msg">{{msg}}</h2>
            {% endfor %}
                
            {% else %}
            <h2>طلب بيع منتج</h2>        
            {% endif %}
                
            <section class="products">
                <div class="product">
                    <div class="image">
                        <img src="{% static 'images/05.png' %}" alt="">
                    </div>
                    <div class="info">
                        <h3>طلب اعادة بيع</h3>
                        <div class="evaluation">
                            <li><i class="fa-solid fa-star"></i></li>
                            <span>4.9</span>
                        </div>
                        <br>
                        <a href="{% url 'order:select-store' %}" class="btn btn-outline">
                            <!-- <li><i class="fa-solid fa-basket-shopping"></i></li> -->
                            طلب اعادة بيع
                        </a>
                    </div>
                </div>
            </section>
            <img src="images/02.png" alt="" class="big-img">
            <img src="images/03.png" alt="" class="big-img">
            <section class="customers">
                <h2>اراء العملاء</h2>
                <div class="box">
                    
                    {% for review in reviews %}
                    <div class="customer">
                        <i class="fa-solid fa-user"></i>
                        <h3> {{review.user}}</h3>
                        <ul class="customer-eval">
                            <li><i class="fa-solid fa-star"></i></li>
                            <li><i class="fa-solid fa-star"></i></li>
                            <li><i class="fa-solid fa-star"></i></li>
                            <li><i class="fa-solid fa-star"></i></li>
                            <li><i class="fa-solid fa-star"></i></li>
                        </ul>
                        <p>سويت الطلب حصل تأخير بس الغلط كان مني مانتبهت للاعلان ان التحويل من 4 عصرا بس الله يعطيهم العافيه وصلت وماقصرو الله يباركلهم فيما رزقكهم يارب
                        </p>
                    </div>
                    {% endfor %}
                        

                </div>
            </section>
            <section class="features">
                <h2>اهم المزايا</h2>
                <div class="box">
                    <div class="feat">
                        <i class="fa-solid fa-box"></i>
                        <h3>مؤسسة خيارات السداد للتجارة</h3>
                        <p>
                            مؤسسة سعودية مسجلة بسجل تجاري رقم 3550150985
                        </p>
                    </div>
                    <div class="feat">
                        <i class="fa-solid fa-box"></i>
                        <h3>بشرعية تامة</h3>
                        <p>جميع المعاملات تتم بطريقة شرعية 100%</p>
                    </div>
                    <div class="feat">
                        <i class="fa-solid fa-box"></i>
                        <h3>سرعة في الإنجاز</h3>
                        <p>
                            خلال دقائق من اتمام طلبك بإذن الله
                        </p>
                    </div>
                </div>
            </section>
            <img src="images/04.png" alt="" class="big-img">
        </div>
    </main>


{% endblock content %}

page/templates/page/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    الصفحة الرئيسية
{% endblock title %}
    


{% block content %}
    <div class="container mt-2">
        <div class="row"></div>
            <div class="card col-md-3" >
                <img src="..." class="card-img-top" alt="...">
                <div class="card-body">
                <h5 class="card-title">طلب إعادة بيع</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="{% url 'order:select-store' %}" class="btn btn-dark">طلب إعادة بيع</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
    

page/templates/page/privacy-policy.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    من نحن؟
{% endblock title %}
    

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock stylesheets %}
    

{% block content %}
    
    <main>
        <div class="container">
            <section class="content">
                <h2 class="title">سياسة الاستخدام والخصوصية</h2>
                <p>
                    {{info.privacy_policy|safe}}
                </p>
            </section>
        </div>
    </main>

{% endblock content %}

page/templates/page/return_policy.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    من نحن؟
{% endblock title %}
    

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock stylesheets %}
    

{% block content %}
    
    <main>
        <div class="container">
            <section class="content">
                <h2 class="title">سياسة الاستبدال والاسترجاع</h2>
                <p>
                    {{info.return_policy|safe}}
                </p>
            </section>
        </div>
    </main>

{% endblock content %}

page/templates/page/terms-conditions.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    من نحن؟
{% endblock title %}
    

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock stylesheets %}
    

{% block content %}
    
    <main>
        <div class="container">
            <section class="content">
                <h2 class="title">الشروط والأحكام</h2>
                <p>
                    {{info.terms_conditions|safe}}
                </p>
            </section>
        </div>
    </main>

{% endblock content %}