order/urls.py
from django.urls import path 
from .views import * 

app_name= 'order' 

urlpatterns = [
    path('new/<int:store_id>/', new_order, name='new-order'), 
    path('new/select-store/', select_store, name='select-store'),
    path('order-sent/', order_sent, name='order-sent'), 
    path('update_products_select/<int:store_id>/', update_products_select, name='update-products-select'), 
    path('details/<str:number>/', show_order, name='show-order'), 
]

page/urls.py
from django.urls import path 
from .views import * 

app_name= 'page'

urlpatterns = [
    path('', index, name='index'), 
    path('about/', about, name='about'), 
    path('terms-and-conditions/', terms_conditions, name='terms-conditions'), 
    path('return-policy/', return_policy, name='return-policy'), 
    path('privacy-policy/', privacy_policy, name='privacy-policy'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls', namespace='page')), 
    path('user/', include('user.urls', namespace='user')), 
    path('order/', include('order.urls', namespace='order')), 
    path('invoice/', include('invoice.urls',namespace='invoice')), 
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path 
from .views import * 

app_name = 'user' 

urlpatterns = [
    path('login/', custom_login, name='custom-login'), 
    path('enter-otp/', enter_otp, name='enter-otp'), 
    path('signup/', signup, name='signup'),
    # path('profile/', profile, name='profile'), 
    path('profile/orders/', user_orders, name='user-orders'), 
    path('logout/', custom_logout, name='custom-logout'), 
    path('profile/', edit_profile,name='profile'), 
]

order/models.py
from django.db import models
from product.models import * 
from user.models import CustomUser 

# Create your models here.

ORDER_STATUS_CHOICES = (
    ('new', 'جديد'), 
    ('approved', 'مقبول'), 
    ("disapproved", "غير مقبول"), 
    ("done", 'مكتمل'), 
)

class Order(models.Model): 
    user = models.ForeignKey(CustomUser, verbose_name='المستخدم', on_delete =models.SET_NULL, null=True, blank=True)   
    store = models.ForeignKey(Store, on_delete=models.SET_NULL, null=True, verbose_name='المتجر')
    # products = models.ManyToManyField(Product, verbose_name="المنتجات") 
    status = models.CharField(max_length=50, choices=ORDER_STATUS_CHOICES, verbose_name="حالة الطلب", null=True, blank=True)
    number = models.CharField(max_length=255, verbose_name='رقم الطلب في المتجر')
    date= models.DateTimeField(verbose_name="التاريخ", auto_now_add=True) 
    total = models.FloatField(verbose_name='الإجمالي', null=True, blank=True) 
    commission_value = models.FloatField(verbose_name='قيمة العمولة', null=True, blank=True) 
    commission_tax_value = models.FloatField(verbose_name='قيمة ضريبة العمولة', null=True,blank=True)
    total_with_tax = models.FloatField(verbose_name='الإجمالي مع ضريبة العمولة', null=True, blank=True)

    def __str__(self): 
        return str(self.number) 
    
    class Meta: 
        verbose_name = 'طلب' 
        verbose_name_plural = 'الطلبات' 


class OrderProduct(models.Model): 
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='رقم الطلب', related_name='products')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, verbose_name="المنتج")
    qty= models.IntegerField(default=1, verbose_name="الكمية") 
    total = models.FloatField(verbose_name='المجموع', blank=True) 

    class Meta: 
        verbose_name_plural = 'المنتجات المطلوبة'



class Review(models.Model): 
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True) 
    order=  models.OneToOneField(Order, on_delete=models.SET_NULL, null=True, blank=True) 
    rate = models.IntegerField(default=5, verbose_name="عدد النجوم")
    content = models.TextField(verbose_name='المحتوى')
    
    class Meta:
        verbose_name = 'تقييم'
        verbose_name_plural = 'التقييمات'

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Bank(models.Model): 
    name = models.CharField(max_length=255, verbose_name="اسم البنك", null = True, blank=True)

    def __str__(self): 
        return self.name 
    
    class Meta: 
        verbose_name= 'بنك'
        verbose_name_plural = 'البنوك'

class CustomUser(AbstractUser): 
    phone_number = models.CharField(max_length=30, verbose_name="رقم الهاتف") 
    # commercial_registration_img = models.ImageField(upload_to='uploads/commercial-registrations/', verbose_name='صورة السجل التجاري')
    full_name = models.CharField(max_length=255, verbose_name="الاسم بالكامل", null=True, blank=True)
    bank_name = models.ForeignKey(Bank, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='اسم البنك') 
    iban = models.CharField(max_length=255, verbose_name="ايبان", null=True, blank=True)
    id_number = models.CharField(max_length=255, verbose_name="رقم الهوية", null=True, blank=True) 
    swift_code = models.CharField(max_length=255, verbose_name='SWIFT CODE', null=True, blank=True)

order/forms.py
from django import forms 
from .models import * 
from django.forms import CheckboxSelectMultiple

user/forms.py
from django import forms
from .models import CustomUser 
from django.contrib.auth.forms import UserCreationForm, UserChangeForm 

class SignupForm(UserCreationForm): 
    # email = forms.EmailField(max_length=254,label='البريد الإلكتروني', widget=forms.TextInput(attrs={'class': 'form-control'}))
    # username = forms.CharField(label='اسم المستخدم', widget=forms.TextInput(attrs={'class': 'form-control'}))
    # phone_number = forms.CharField(label="رقم الجوال", widget=forms.TextInput(attrs={'class': 'form-control'}))
    # password1 = forms.CharField(label="كلمة المرور", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    # password2 = forms.CharField(label="تأكيد كلمة المرور", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta: 
        model = CustomUser 
        fields = ['email', 'username', 'phone_number', 'password1', 'password2']



class UpdateUserForm(UserChangeForm): 
    class Meta: 
        model = CustomUser 
        fields = [
            'email', 'username', 'phone_number', 'full_name', 'bank_name', 'iban', 'id_number', 'swift_code'
        ]
        exclude = ('password1', 'password2')

order/views.py
from django.shortcuts import render, redirect 
from .models import * 
from django.contrib.auth.decorators import login_required
import json 
from page.models import *

# Create your views here.

@login_required(login_url='/user/login/') 
def new_order(request, store_id): 
    info = Info.objects.first() 
    store = Store.objects.get(id=store_id) 
    products = Product.objects.filter(store=store) 


    if request.POST: 
        products_list = request.POST.get('products_list') 
        order_number= request.POST.get('order_number')
        if products_list is not None: 

            total_counter = 0 
            order = Order.objects.create(
                user=request.user, 
                store=store, 
                status='new', 
                number=order_number 
            ) 
            
            lst = products_list.split('-') 
            for i in lst: 
                sub_list = i.split(',') 
                if sub_list[0] !="" and len(sub_list) > 1: 
                    product_id = sub_list[0] 
                    product_qty = sub_list[1] 
                    total = sub_list[2]
                    order_product = OrderProduct.objects.create( 
                    order =order, product=Product.objects.get(id=product_id), 
                    qty = product_qty, 
                    total=total 
                )
                elif sub_list[0] == "" and len(sub_list) > 1: 
                    product_id = sub_list[1] 
                    product_qty = sub_list[2] 
                    total = sub_list[3]
                    order_product = OrderProduct.objects.create( 
                        order =order, product=Product.objects.get(id=product_id), 
                        qty = product_qty, 
                        total=total 
                    )
                
            
            for product in order.products.all(): 
                total_counter += product.total 
            
            order.total = total_counter

            tax = 15/100 
            commission = 5/ 100 

            commission_value = order.total * commission 
            tax_vlaue = commission_value * tax 

            order.total_with_tax = order.total + tax_vlaue + commission_value
            order.commission_value = commission_value 
            order.commission_tax_value = tax_vlaue

            order.save() 


    context = {
        'info': info, 
        'products': products, 
        'store_id': store_id

    } 
    return render(request, 'order/new-order.html', context) 


def order_sent(request): 
    context=  {} 
    return render(request, 'order/order-sent.html', context)

def update_products_select(request, store_id): 
    store = Store.objects.get(id=store_id) 
    products = Product.objects.filter(store=store) 

    context = { 
        'products': products, 
    }

    return render(request, 'order/products-select.html', context)


def select_store(request): 
    stores = Store.objects.all() 
    if request.POST: 
        store_input = request.POST.get('store-input') 
        if store_input is not None: 
            return redirect('order:new-order', store_input)
    context = {
        'stores': stores, 
    }
    return render(request, 'order/select-store.html', context)



@login_required
def show_order(request, number):
    order = Order.objects.filter(user=request.user).get(number=number)
    context=  {
        'order': order,
    } 
    return render(request, 'order/show-order.html', context)

user/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages 
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied 
from .utils import send_otp, generate_otp 
from .models import CustomUser 
from .forms import SignupForm, UpdateUserForm
from order.models import * 

# Create your views here.
def custom_login(request): 
    if request.user.is_authenticated: 
        return redirect('page:index')
    else: 
        if request.POST: 
            phone_number = request.POST['phone_number']
            user = CustomUser.objects.filter(phone_number=phone_number).first() 
            if user:                 
                otp = generate_otp() 
                send_otp(phone_number, otp)
                request.session['otp'] = otp 
                request.session['phone_number'] = phone_number 

                return redirect('user:enter-otp')
            else: 
                messages.error(request, "رقم الهاتف غير صحيح") 


    context = {}
    return render(request, 'user/login.html', context)

def enter_otp(request): 
    if request.user.is_authenticated: 
        return redirect('user:profile') 
    else: 
        if request.POST: 
            otp = request.POST['otp'] 
            stored_otp= request.session['otp']
            phone_number = request.session['phone_number']
            user = CustomUser.objects.filter(phone_number=phone_number).first() 

            if str(otp) == str(stored_otp): 
                login(request, user)
                messages.add_message(request, messages.SUCCESS, f"أهلا، {user.username}")
                return redirect('page:index') 

    context = {} 
    return render(request, 'user/enter-otp.html', context=context)


def signup(request): 
    if request.POST: 
        form = SignupForm(request.POST) 
        if form.is_valid(): 
            form.save() 
            # redirect to login page 
            return redirect('user:custom-login') 
    else: 
        form = SignupForm() 
    context = {
        'form': form 
    } 
    return render(request, 'user/signup.html', context= context)


@login_required(login_url='/user/login/')
def profile(request): 
    form = UpdateUserForm(instance=request.user) 
    if request.POST: 
        form = UpdateUserForm(request.POST, instance=request.user)
        if form.is_valid(): 
            form.save() 
            return redirect('user:profile') 
    context = {
        'form': form
    } 
    return render(request, 'user/profile.html', context=context)


def custom_logout(request): 
    logout(request) 
    context = {} 
    return render(request, 'user/logged-out.html', context) 


@login_required
def user_orders(request): 
    user = request.user 

    orders = Order.objects.filter(user=user) 

    context = {
        'orders': orders 
    }

    return render(request, 'user/profile-orders.html', context)


@login_required
def edit_profile(request):
    form = UpdateUserForm(instance=request.user) 
    if request.POST:
        form = UpdateUserForm(request.POST, instance=request.user) 
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "تم حفظ التعديلات بنجاح")
            return redirect('user:profile')
    context = {
        'form': form, 
    } 
    return render(request, 'user/profile-edit.html', context)

user/templates/user/enter-otp.html
{% extends 'base.html' %}

{% block title %}
    أدخل رمز التحقق
{% endblock title %}
    

{% block content %}
    <div class="container mt-2">
        <h1>أدخل رمز التحقق</h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">رمز التحقق</label>
                <input type="text" name="otp" class="form-control">
                <p class="form-text">سيصلك رمز الجوال مكون من 5 أرقام</p>
            </div>
            <button type="submit" class="btn btn-dark">تحقق</button>
        </form>
    </div>
{% endblock content %}
    

user/templates/user/logged-out.html
{% extends 'base.html' %}

{% block title %}
    تسجيل خروج
{% endblock title %}
    


{% block content %}
    <div class="container mt-2">
        <h2 class="mb-3">تم تسجيل خروج بنجاح</h2>
        <a href="{% url 'page:index' %}" class="mt-2 btn btn-dark">العودة للصفحة الرئيسية</a>
    </div>
{% endblock content %}
    

user/templates/user/login.html
{% extends 'base.html' %}


{% block title %}
    تسجيل الدخول
{% endblock title %}
    

{% block content %}
<div class="container mt-2">
    <h1>تسجيل الدخول</h1>

    <form method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label class="form-label">رقم الجوال</label>
            <input type="text" class="form-control" name="phone_number" >
            <p class="form-text">اكتب رقم الجوال المسجل في الموقع</p>
        </div>
        <button type="submit" class="btn btn-dark">الحصول على الرمز</button>
        <br>
        <a href="{% url 'user:signup' %}">ليس لديك حساب؟ إنشاء حساب جديد</a>

    </form>    
</div>
{% endblock content %}
    

user/templates/user/orders.html
{% extends 'base.html' %}

{% block title %}
    الطلبات
{% endblock title %}
    

{% block content %}

<section>
    <div class="container mt-2 mb-3">
        <h2>الطلبات</h2>

        <div class="row">
            
            {% for order in orders %}
                <div class="col-md-3 card p-3 " >
                    <h5>رقم الطلب: {{order.id}}</h5>
                    <h6>
                        حالة الطلب: 
                        {{order.get_status_display}}
                    </h6>
                    <h6>
                        الإجمالي: 
                        {{order.total}}
                    </h6>
                    <h6>
                        عدد المنتجات: 
                        {{order.products.count}}
                    </h6>
                    <a href="" class="mt-3 btn btn-dark">تفاصيل</a>
                </div>
            {% endfor %}
                

        </div>

    </div>
</section>


{% endblock content %}
    

user/templates/user/profile-base.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
{% endblock title %}
    

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock stylesheets %}

{% block content %}    
    <main>
        <div class="container">
            <div class="top-img"></div>
            <section class="content">
                <div class="sidebar">
                    <ul>
                        <li>
                            <a href="">
                                <i class="fa-regular fa-bell"></i>
                                الاشعارات
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'user:user-orders' %}">
                                <i class="fa-brands fa-first-order"></i>
                                الطلبات
                            </a>
                        </li>
                        <!-- <li>
                            <a href="">
                                <i class="fa-solid fa-cart-plus"></i>
                                طلبات بانتظار الدفع
                            </a>
                        </li> -->
                        <!-- <li>
                            <a href="">
                                <i class="fa-regular fa-star"></i>
                                الامنيات
                            </a>
                        </li> -->
                        <li>
                            <a href="{% url 'user:profile' %}">
                                <i class="fa-regular fa-user"></i>
                                حسابي
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'user:custom-logout' %}">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                                تسجيل الخروج
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="info">
                    <h3 class="title">
                        
                        {% block section_title %}
                            
                        {% endblock section_title %}
                            
                    </h3>
                    <div class="center">
                        
                        {% block section_content %}
                            
                        {% endblock section_content %}
                            
                    </div>
                </div>
            </section>
        </div>
    </main>

{% endblock content %}

user/templates/user/profile-edit.html
{% extends 'user/profile-base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}
    تعديل الملف الشخصي
{% endblock title %}

{% block section_title %}
تعديل الملف الشخصي
{% endblock section_title %}
    
{% block section_content %}

<form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-dark">حفظ التعديلات</button>
</form>

{% endblock section_content %}

user/templates/user/profile-orders.html
{% extends 'user/profile-base.html' %}
{% load static %}


{% block title %}
    الطلبات
{% endblock title %}


{% block section_title %}
    الطلبات
{% endblock section_title %}
    


{% block section_content %}
<!-- <h3>هنا تظهر طلبات المستخدم</h3> -->

<style>
    .products {
        width: 100% !important;
        display: flex; 
        flex-wrap: wrap;
        gap: 1rem; 
        justify-content: center;
    }
    .products img {
        width: 200px; 
    }
</style>
<div class="container">

<section class="products mt-3">
    {% for order in orders %}
    <div class="product">
        <div class="image">
            <img src="{% static 'images/05.png' %}" alt="">
        </div>
        <div class="info">
            <h3>{{order.number}}</h3>
            <h4>{{order.get_status_display}}</h4>
            <!-- <div class="evaluation">
                <li><i class="fa-solid fa-star"></i></li>
                <span>4.9</span>
            </div> -->
            <br>
            <a href="{% url 'order:show-order' order.number %}" class="btn btn-outline">
                <!-- <li><i class="fa-solid fa-basket-shopping"></i></li> -->
                تفاصيل الطلب
            </a>
        </div>
    </div>
    {% endfor %}
</section>
    

{% endblock section_content %}
    

user/templates/user/profile.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    الملف الشخصي
{% endblock title %}
    

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
          
{% endblock stylesheets %}

{% block content %}
    
    
    <main>
        <div class="container">
            <div class="top-img"></div>
            <section class="content">
                <div class="sidebar">
                    <ul>
                        <li>
                            <a href="">
                                <i class="fa-regular fa-bell"></i>
                                الاشعارات
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <i class="fa-brands fa-first-order"></i>
                                الطلبات
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <i class="fa-solid fa-cart-plus"></i>
                                طلبات بانتظار الدفع
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <i class="fa-regular fa-star"></i>
                                الامنيات
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <i class="fa-regular fa-user"></i>
                                حسابي
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                                تسجيل الخروج
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="info">
                    <h3 class="title">الاشعارات</h3>
                    <div class="center">
                        <!-- <div class="circle"></div> -->
                        <h3>لا توجد اشعارات</h3>
                    </div>
                </div>
            </section>
        </div>
    </main>

    {% endblock content %}

user/templates/user/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    إنشاء حساب
{% endblock title %}


{% block content %}
<style>
    form > div { 
        margin-bottom: 1.5rem;
    }
    form > div > label {
        margin-bottom: 5px;
    }
</style>
    <div class="container mt-2">
        <h1>إنشاء حساب</h1>
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-dark">إنشاء حساب</button>
            <br>
            <a href="{% url 'user:custom-login' %}">هل لديك حساب بالفعل؟ تسجيل دخول</a>
        </form>
    </div>
{% endblock content %}
    