page/urls.py
from django.urls import path 
from .views import * 

app_name= 'page'

urlpatterns = [
    path('', index, name='index'), 
    path('about/', about, name='about'), 
    path('terms-and-conditions/', terms_conditions, name='terms-conditions'), 
    path('return-policy/', return_policy, name='return-policy'), 
    path('privacy-policy/', privacy_policy, name='privacy-policy'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls', namespace='page')), 
    path('user/', include('user.urls', namespace='user')), 
    path('order/', include('order.urls', namespace='order')), 
    path('invoice/', include('invoice.urls',namespace='invoice')), 
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path 
from .views import * 

app_name = 'user' 

urlpatterns = [
    path('login/', custom_login, name='custom-login'), 
    path('enter-otp/', enter_otp, name='enter-otp'), 
    path('signup/', signup, name='signup'),
    # path('profile/', profile, name='profile'), 
    path('profile/orders/', user_orders, name='user-orders'), 
    path('logout/', custom_logout, name='custom-logout'), 
    path('profile/', edit_profile,name='profile'), 
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    {% block title %}
    {% endblock title %}
        </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Changa:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet"> 
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> -->

    <!-- <link rel="stylesheet" href="{% static 'css/main.css' %}">  -->
        
        {% block stylesheets %}
          
        {% endblock stylesheets %}
          
    <!-- <link rel="stylesheet" href="{% static 'css/profile.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">

</head>
<body>

  <header>
    <div class="container">
        <nav>
            <div class="right">
                <div class="menu-bar">
                    <i class="fa-solid fa-bars"></i>
                </div>
                <a href="{% url 'page:index' %}">
                    <img src="{% static 'images/logo.webp' %}" alt="" class="logo">
                </a>
            </div>
            <div class="center">
                <input type="search" class="input" placeholder="ادخل كلمة البحث: ">
            </div>
            <div class="left">
                <ul>
                    <li class="profile-icon">
                        <!-- <i class="fa-solid fa-user"></i> -->
                        حسابي
                        <ul class="dropdown-menu">
                            <li>
                                <i class="fa-regular fa-bell"></i>
                                <a href="profile.html">الاشعارات</a>
                            </li>
                            <li>
                                <i class="fa-brands fa-first-order"></i>
                                <a href="{% url 'user:user-orders' %}">الطلبات</a>
                            </li>
                            <li>
                                <i class="fa-solid fa-cart-plus"></i>
                                <a href="profile.html">طلبات بانتظار الدفع</a>
                            </li>
                            <li>
                                <i class="fa-regular fa-star"></i>
                                <a href="profile.html">الامنيات</a>
                            </li>
                            <li>
                                <i class="fa-regular fa-user"></i>
                                <a href="{% url 'user:profile' %}">حسابي</a>
                            </li>
                            <li>
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                                <a href="{% url 'user:custom-logout' %}">تسجيل الخروج</a>
                            </li>
                        </ul>
                    </li>
                    <li><i class="fa-solid fa-basket-shopping"></i></li>
                    <li>0 ر.س</li>
                </ul>
            </div>
        </nav>
        <div class="responsive-menu">
            <input type="search" class="input" placeholder="ادخل كلمة البحث: ">
        </div>            
    </div>
</header>

    <div class="content-wrapper">

      {% block content %}
      
      {% endblock content %}
    </div>
        
    <footer>
      <div class="container">
          <div class="about">
              <h2>خدمة فزعة</h2>
              <p>خدمة فزعة هي خدمة تفزعلك في اي من الخدمات الخاصة بالتجارة مثل بيع منتج او شراء منتج او توصيل وغيرها...</p>
              <span>الرقم الضريبي</span>
              <p>054 021 3290</p>
          </div>
          <div class="links">
              <h2>روابط مهمة</h2>
              <ul>
                  <li><a href="{% url 'page:about' %}">ما هي خدمة فزعة؟</a></li>
                  <li><a href="{% url 'page:terms-conditions' %}">الشروط والاحكام</a></li>
                  <li><a href="{% url 'page:return-policy' %}">سياسية الاستبدال والاسترجاع</a></li>
                  <li><a href="{% url 'page:privacy-policy' %}">سياسية الاستخدام والخصوصية</a></li>
              </ul>
          </div>
          <div class="contact">
              <h2>تواصل معنا</h2>
              <ul>
                  <li>
                      <i class="fa-brands fa-whatsapp"></i>
                      054 021 3290
                  </li>
                  <li>
                      <i class="fa-solid fa-phone"></i>
                      056 525 8902
                  </li>
                  <li>
                      <i class="fa-solid fa-mobile"></i>
                      057 089 0457
                  </li>
                  <li>
                      <i class="fa-solid fa-envelope"></i>
                      djangodeveloper6@gmail.com
                  </li>
              </ul>
          </div>
      </div>
  </footer>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/user_printer.html
{% load static %}
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{order.number}}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200..1000&display=swap" rel="stylesheet">
    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js"></script>

    <style>
        * {
            font-family: "Cairo", sans-serif;
            font-family: "Rubik", sans-serif;  
            font-optical-sizing: auto;
        }
        .order__header { 
            padding: 1rem 0;
        }

        .website__logo {
            width: 400px;
            max-width: 100% !important;
        }

    </style>
</head>
<body>
<div id="container">

    <div class="container">
        <div class="row">
            {{order.date}}
        </div>
        <br>
        <br>
        <center>
            <img class="website__logo" src="{% static 'imgs/invoice/fazaa-logo.webp' %}" alt="">
        </center>
        <div class="row order__header">
            <div class="col-md-6">
                <h6>
                    رقم الطلب: {{order.number}}
                </h6>
            </div>
            <div class="col-md-6">
                <h6>
                    المتجر: {{order.store}}
                </h6>
            </div>
            <div class="row order_user">
                <div class="col-md-6">
                    <h6>
                        اسم العميل: 
                        {{order.user}}
                    </h6>
                </div>
                <div class="col-md-6">
                    <h6>
                        رقم الجوال: 
                        {{order.user.phone_number}}
                    </h6>
                </div>
            </div>
        </div>




    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">اسم المنتج</th>
            <th scope="col">الكمية</th>
            <th scope="col">سعر إعادة البيع</th>
            <th scope="col">الإجمالي</th>
          </tr>
        </thead>
        <tbody>
        
        {% for product in order.products.all %}  
          <tr>
            <th scope="row">{{product.id}}</th>
            <td>{{product.product.name}}</td>
            <td>{{product.qty}}</td>
            <td>{{product.product.selling_price}} ريال</td>
            <td>{{product.total}}</td>
          </tr>
        {% endfor %}

        </tbody>
    </table>


    <div>
        <h6>عمولة إعادة البيع: 5%</h6>
    </div>
    <div>
        <h6>
            قيمة العمولة: {{order.commission_value}} ريال سعودي
        </h6>
    </div>
    <div>
        <h6>الضريبة: 15%</h6>
    </div>
    <div>
        <h6>
            قيمة ضريبة العمولة: {{order.commission_tax_value}} ريال سعودي
        </h6>
    </div>
    <div>
        <h6>الإجمالي: {{order.total_with_tax}} ريال سعودي</h6>
    </div>
    <hr>
    <div>
        <h6>إجمالي ما سيتم تحويله للعميل: {{order.total}} ريال سعودي</h6>
    </div>

    <div>
        <h5>
            سياسة الاستبدال والاسترجاع
        </h5>
        <p>
            نظراً لكون الخدمة عبارة عن اعادة بيع لمشتروات العميل فإنة :

بعد اتمام البيع وتحويل الاموال لا يمكنك مطلقا استبدال او استرجاع المنتج او الخدمة .
        </p>
    </div>

    <div>
        <h5>الشروط والأحكام</h5>
        <ol>
            <li>
                تسري الاتفاقية من تاريخ اتمام الطلب
            </li>
            <li>
                المنتج يكون موضح في الطلب وبالكمية المحددة من قبل العميل
            </li>
            <li>
                بعد اتمام العميل لطلب اعادة البيع واستلامنا للمنتجات سيتم اعادة بيعها مقابل السعر الموضح في صفحة المنتج
            </li>
            <li>
                يتحمل العميل اي خطاء في البيانات البنكية المدخلة .
            </li>
            <li>
                بعد اتمام بيع المنتجات اللتي قمت بشراءها سيتم تحويل المبلغ للحساب البنكي الذي قام العميل بادخالة .
            </li>
            <li>
                باتمام الطلب فالعميل يقر بتوكيلة لنا في بيع المنتجات وتحويل المبلغ الموضح نتيجة اعادة بيعها من قبلنا
            </li>
            <li>
                خيارات السداد للتجارة تقدم خدمة للعميل يتم خلالها استلام و اعادة بيع مشترواته .
            </li>
            <li>
                بقراءة هذه الشروط والاحكام يعد العميل باتمامة للطلب ملم بما يترتب على ذلك .
            </li>
            <li>
                تتم الخدمة خلال 48 ساعه كحد اقصى من استلامنا لطلب اعادة البيع
            </li>
        </ol>
    </div>

    <div>
        <h5>إمكانية إلغاء الحساب</h5>
        <p>
            في حال قررتم إلغاء الحساب يحتفظ موقع فزعة بالفواتير لمدة عامين حل تطلب الأمر.
        </p>
    </div>


    </div>


</div>

    <script>
        $(document).ready(function(){

            window.print()
        
        })
</script>
    

</body>
</html>